version: "3.9"


services:
  workernode0:
    build: ./workerNode
    restart: always
    container_name: workernode0
    ports:
      - "8080:8080"
    networks:
      - my-network
    
  workernode1:
    build: ./workerNode
    restart: always
    container_name: workernode1
    ports:
      - "8081:8080"
    networks:
      - my-network


  workernode2:
    build: ./workerNode
    restart: always
    container_name: workernode2
    ports:
      - "8082:8080"
    networks:
      - my-network


  workernode3:
    build: ./workerNode
    restart: always
    container_name: workernode3
    ports:
      - "8083:8080"
    networks:
      - my-network


  bootstrap:
    build: ./bootstrappingNode
    restart: always
    container_name: bootstrap
    ports:
      - "8000:8080"
    depends_on:
      - workernode0
      - workernode1
      - workernode2
      - workernode3
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
